create table if not exists clientes
(
    client_id  varchar(255),
    contrasena varchar(255) not null,
    estado     boolean      not null,
    id         bigint       not null
);

alter table clientes
    owner to postgres;

alter table clientes
    add primary key (id);

alter table clientes
    add constraint ukmsdnyb9nn573txdo47aa1p9nw
        unique (client_id);

create table if not exists personas
(
    id             bigint generated by default as identity,
    created_at     timestamp(6),
    direccion      varchar(255) not null,
    edad           bigint       not null,
    genero         varchar(255) not null,
    identificacion varchar(255) not null,
    nombre         varchar(255) not null,
    telefono       varchar(255) not null
);

alter table personas
    owner to postgres;

alter table personas
    add primary key (id);

alter table clientes
    add constraint fktk4yna9cqo54xshjc9dpgbmc8
        foreign key (id) references personas;

create table if not exists cuentas
(
    id            bigint generated by default as identity,
    client_id     varchar(255)     not null,
    created_at    timestamp(6),
    estado        boolean          not null,
    numero_cuenta varchar(255)     not null,
    saldo_inicial double precision not null,
    tipo_cuenta   varchar(255)     not null
);

alter table cuentas
    owner to postgres;

alter table cuentas
    add primary key (id);

alter table cuentas
    add constraint uk7h7mqvcau3mcl0mbrkdrt7fnh
        unique (numero_cuenta);

alter table cuentas
    add constraint cuentas_tipo_cuenta_check
        check ((tipo_cuenta)::text = ANY
               ((ARRAY ['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[]));

create table if not exists movimientos
(
    id              bigint generated by default as identity,
    created_at      timestamp(6),
    fecha           timestamp(6),
    saldo           double precision not null,
    tipo_movimiento varchar(255)     not null,
    valor           double precision not null,
    cuenta_id       bigint
);

alter table movimientos
    owner to postgres;

alter table movimientos
    add primary key (id);

alter table movimientos
    add constraint fk4moe88hxuohcysas5h70mdc09
        foreign key (cuenta_id) references cuentas;


-- INSERTS

-- Clientes
INSERT INTO public.clientes (client_id, contrasena, estado, id) VALUES ('C123', '1234', true, 11);
INSERT INTO public.clientes (client_id, contrasena, estado, id) VALUES ('C213', '5678', true, 7);
INSERT INTO public.clientes (client_id, contrasena, estado, id) VALUES ('C231', '1245', true, 10);

-- Personas
INSERT INTO public.personas (id, nombre, created_at, direccion, edad, genero, identificacion, telefono) VALUES (11, 'Jose Lema', '2024-05-28 22:14:56.128444', 'Otalvo sn y principal', 18, 'Masculino', '1234567890', '098254785');
INSERT INTO public.personas (id, nombre, created_at, direccion, edad, genero, identificacion, telefono) VALUES (10, 'Juan Osorio', '2024-05-28 22:05:52.488893', '13 junio y Equinoccial', 20, 'Masculino', '2143567890', '098874587');
INSERT INTO public.personas (id, nombre, created_at, direccion, edad, genero, identificacion, telefono) VALUES (7, 'Marianela Montalvo', '2024-05-28 21:48:35.013796', 'Amazonas y NNUU', 19, 'Femenino', '2134567890', '097548965');

-- Cuentas
INSERT INTO public.cuentas (id, client_id, created_at, estado, numero_cuenta, saldo_inicial, tipo_cuenta) VALUES (1, 'C123', '2024-05-28 22:40:52.687616', true, '478758', 1425, 'AHORROS');
INSERT INTO public.cuentas (id, client_id, created_at, estado, numero_cuenta, saldo_inicial, tipo_cuenta) VALUES (2, 'C213', '2024-05-28 22:43:22.010353', true, '225487', 700, 'CORRIENTE');
INSERT INTO public.cuentas (id, client_id, created_at, estado, numero_cuenta, saldo_inicial, tipo_cuenta) VALUES (3, 'C231', '2024-05-28 22:44:16.326301', true, '495878', 150, 'AHORROS');
INSERT INTO public.cuentas (id, client_id, created_at, estado, numero_cuenta, saldo_inicial, tipo_cuenta) VALUES (4, 'C213', '2024-05-28 22:45:20.089842', true, '496825', 0, 'AHORROS');
INSERT INTO public.cuentas (id, client_id, created_at, estado, numero_cuenta, saldo_inicial, tipo_cuenta) VALUES (8, 'C123', '2024-05-29 01:34:28.472544', true, '585545', 1000, 'CORRIENTE');

-- Movimientos
INSERT INTO public.movimientos (id, created_at, fecha, saldo, tipo_movimiento, valor, cuenta_id) VALUES (2, '2024-05-29 04:17:39.581257', '2024-05-29 04:17:39.581257', 2000, 'RETIRO', -575, 1);
INSERT INTO public.movimientos (id, created_at, fecha, saldo, tipo_movimiento, valor, cuenta_id) VALUES (3, '2024-05-29 04:18:43.382329', '2024-05-29 04:18:43.382329', 100, 'DEPOSITO', 600, 2);
INSERT INTO public.movimientos (id, created_at, fecha, saldo, tipo_movimiento, valor, cuenta_id) VALUES (4, '2024-05-29 04:20:51.984311', '2024-05-29 04:20:51.984311', 0, 'DEPOSITO', 150, 3);
INSERT INTO public.movimientos (id, created_at, fecha, saldo, tipo_movimiento, valor, cuenta_id) VALUES (5, '2024-05-29 04:23:55.611323', '2024-05-29 04:23:55.611323', 540, 'RETIRO', -540, 4);
