version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbdevsuchallenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  customer-service:
    build: ./ms-customer
    ports:
      - "8081:8070"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbdevsuchallenge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres-db

  account-service:
    build: ./ms-account
    ports:
      - "8082:8071"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/dbdevsuchallenge
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres-db

volumes:
  postgres-data:
